In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [25]:
df=pd.read_csv("/content/drive/MyDrive/14 days of ML/Feature Engneering/house-prices.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [26]:
print("Shape:\n",df.shape)

Shape:
 (1460, 81)

In [27]:
print("Description:\n",df.describe)

Description:
 <bound method NDFrame.describe of         Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0            Lvl    AllPub    Inside       Gtl      CollgCr       Norm
1            Lvl    AllPub       FR2       Gtl      Veenker      Feedr
2            Lvl    AllPub    Inside       Gtl      CollgCr       Norm
3            Lvl    AllPub    Corner       Gtl      Crawfor       Norm
4            Lvl    AllPub       FR2       Gtl      NoRidge       Norm
...          ...       ...       ...       ...          ...        ...
1455         Lvl    AllPub    Inside       Gtl      Gilbert       Norm
1456         Lvl    AllPub    Inside       Gtl       NWAmes       Norm
1457         Lvl    AllPub    Inside       Gtl      Crawfor       Norm
1458         Lvl    AllPub    Inside       Gtl        NAmes       Norm
1459         Lvl    AllPub    Inside       Gtl      Edwards       Norm

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0          Norm     1Fam     2Story            7            5       2003
1          Norm     1Fam     1Story            6            8       1976
2          Norm     1Fam     2Story            7            5       2001
3          Norm     1Fam     2Story            7            5       1915
4          Norm     1Fam     2Story            8            5       2000
...         ...      ...        ...          ...          ...        ...
1455       Norm     1Fam     2Story            6            5       1999
1456       Norm     1Fam     1Story            6            6       1978
1457       Norm     1Fam     2Story            7            9       1941
1458       Norm     1Fam     1Story            5            6       1950
1459       Norm     1Fam     1Story            5            6       1965

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0             2003     Gable  CompShg     VinylSd     VinylSd    BrkFace
1             1976     Gable  CompShg     MetalSd     MetalSd        NaN
2             2002     Gable  CompShg     VinylSd     VinylSd    BrkFace
3             1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN
4             2000     Gable  CompShg     VinylSd     VinylSd    BrkFace
...            ...       ...      ...         ...         ...        ...
1455          2000     Gable  CompShg     VinylSd     VinylSd        NaN
1456          1988     Gable  CompShg     Plywood     Plywood      Stone
1457          2006     Gable  CompShg     CemntBd     CmentBd        NaN
1458          1996       Hip  CompShg     MetalSd     MetalSd        NaN
1459          1965     Gable  CompShg     HdBoard     HdBoard        NaN

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
0          196.0        Gd        TA      PConc       Gd       TA
1            0.0        TA        TA     CBlock       Gd       TA
2          162.0        Gd        TA      PConc       Gd       TA
3            0.0        TA        TA     BrkTil       TA       Gd
4          350.0        Gd        TA      PConc       Gd       TA
...          ...       ...       ...        ...      ...      ...
1455         0.0        TA        TA      PConc       Gd       TA
1456       119.0        TA        TA     CBlock       Gd       TA
1457         0.0        Ex        Gd      Stone       TA       Gd
1458         0.0        TA        TA     CBlock       TA       TA
1459         0.0        Gd        TA     CBlock       TA       TA

     BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  \
0              No          GLQ         706          Unf           0
1              Gd          ALQ         978          Unf           0
2              Mn          GLQ         486          Unf           0
3              No          ALQ         216          Unf           0
4              Av          GLQ         655          Unf           0
...           ...          ...         ...          ...         ...
1455           No          Unf           0          Unf           0
1456           No          ALQ         790          Rec         163
1457           No          GLQ         275          Unf           0
1458           Mn          GLQ          49          Rec        1029
1459           No          BLQ         830          LwQ         290

      BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  \
0           150          856    GasA        Ex          Y      SBrkr
1           284         1262    GasA        Ex          Y      SBrkr
2           434          920    GasA        Ex          Y      SBrkr
3           540          756    GasA        Gd          Y      SBrkr
4           490         1145    GasA        Ex          Y      SBrkr
...         ...          ...     ...       ...        ...        ...
1455        953          953    GasA        Ex          Y      SBrkr
1456        589         1542    GasA        TA          Y      SBrkr
1457        877         1152    GasA        Ex          Y      SBrkr
1458          0         1078    GasA        Gd          Y      FuseA
1459        136         1256    GasA        Gd          Y      SBrkr

      1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
0          856       854             0       1710             1             0
1         1262         0             0       1262             0             1
2          920       866             0       1786             1             0
3          961       756             0       1717             1             0
4         1145      1053             0       2198             1             0
...        ...       ...           ...        ...           ...           ...
1455       953       694             0       1647             0             0
1456      2073         0             0       2073             1             0
1457      1188      1152             0       2340             0             0
1458      1078         0             0       1078             1             0
1459      1256         0             0       1256             1             0

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  \
0            2         1             3             1          Gd
1            2         0             3             1          TA
2            2         1             3             1          Gd
3            1         0             3             1          Gd
4            2         1             4             1          Gd
...        ...       ...           ...           ...         ...
1455         2         1             3             1          TA
1456         2         0             3             1          TA
1457         2         0             4             1          Gd
1458         1         0             2             1          Gd
1459         1         1             3             1          TA

      TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt  \
0                8        Typ           0         NaN     Attchd       2003.0
1                6        Typ           1          TA     Attchd       1976.0
2                6        Typ           1          TA     Attchd       2001.0
3                7        Typ           1          Gd     Detchd       1998.0
4                9        Typ           1          TA     Attchd       2000.0
...            ...        ...         ...         ...        ...          ...
1455             7        Typ           1          TA     Attchd       1999.0
1456             7       Min1           2          TA     Attchd       1978.0
1457             9        Typ           2          Gd     Attchd       1941.0
1458             5        Typ           0         NaN     Attchd       1950.0
1459             6        Typ           0         NaN     Attchd       1965.0

     GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
0             RFn           2         548         TA         TA          Y
1             RFn           2         460         TA         TA          Y
2             RFn           2         608         TA         TA          Y
3             Unf           3         642         TA         TA          Y
4             RFn           3         836         TA         TA          Y
...           ...         ...         ...        ...        ...        ...
1455          RFn           2         460         TA         TA          Y
1456          Unf           2         500         TA         TA          Y
1457          RFn           1         252         TA         TA          Y
1458          Unf           1         240         TA         TA          Y
1459          Fin           1         276         TA         TA          Y

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0              0           61              0          0            0
1            298            0              0          0            0
2              0           42              0          0            0
3              0           35            272          0            0
4            192           84              0          0            0
...          ...          ...            ...        ...          ...
1455           0           40              0          0            0
1456         349            0              0          0            0
1457           0           60              0          0            0
1458         366            0            112          0            0
1459         736           68              0          0            0

      PoolArea PoolQC  Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
0            0    NaN    NaN         NaN        0       2    2008       WD
1            0    NaN    NaN         NaN        0       5    2007       WD
2            0    NaN    NaN         NaN        0       9    2008       WD
3            0    NaN    NaN         NaN        0       2    2006       WD
4            0    NaN    NaN         NaN        0      12    2008       WD
...        ...    ...    ...         ...      ...     ...     ...      ...
1455         0    NaN    NaN         NaN        0       8    2007       WD
1456         0    NaN  MnPrv         NaN        0       2    2010       WD
1457         0    NaN  GdPrv        Shed     2500       5    2010       WD
1458         0    NaN    NaN         NaN        0       4    2010       WD
1459         0    NaN    NaN         NaN        0       6    2008       WD

     SaleCondition  SalePrice
0           Normal     208500
1           Normal     181500
2           Normal     223500
3          Abnorml     140000
4           Normal     250000
...            ...        ...
1455        Normal     175000
1456        Normal     210000
1457        Normal     266500
1458        Normal     142125
1459        Normal     147500

[1460 rows x 81 columns]>

In [28]:
print("Info:\n",df.info)

Info:
 <bound method DataFrame.info of         Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0            Lvl    AllPub    Inside       Gtl      CollgCr       Norm
1            Lvl    AllPub       FR2       Gtl      Veenker      Feedr
2            Lvl    AllPub    Inside       Gtl      CollgCr       Norm
3            Lvl    AllPub    Corner       Gtl      Crawfor       Norm
4            Lvl    AllPub       FR2       Gtl      NoRidge       Norm
...          ...       ...       ...       ...          ...        ...
1455         Lvl    AllPub    Inside       Gtl      Gilbert       Norm
1456         Lvl    AllPub    Inside       Gtl       NWAmes       Norm
1457         Lvl    AllPub    Inside       Gtl      Crawfor       Norm
1458         Lvl    AllPub    Inside       Gtl        NAmes       Norm
1459         Lvl    AllPub    Inside       Gtl      Edwards       Norm

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0          Norm     1Fam     2Story            7            5       2003
1          Norm     1Fam     1Story            6            8       1976
2          Norm     1Fam     2Story            7            5       2001
3          Norm     1Fam     2Story            7            5       1915
4          Norm     1Fam     2Story            8            5       2000
...         ...      ...        ...          ...          ...        ...
1455       Norm     1Fam     2Story            6            5       1999
1456       Norm     1Fam     1Story            6            6       1978
1457       Norm     1Fam     2Story            7            9       1941
1458       Norm     1Fam     1Story            5            6       1950
1459       Norm     1Fam     1Story            5            6       1965

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0             2003     Gable  CompShg     VinylSd     VinylSd    BrkFace
1             1976     Gable  CompShg     MetalSd     MetalSd        NaN
2             2002     Gable  CompShg     VinylSd     VinylSd    BrkFace
3             1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN
4             2000     Gable  CompShg     VinylSd     VinylSd    BrkFace
...            ...       ...      ...         ...         ...        ...
1455          2000     Gable  CompShg     VinylSd     VinylSd        NaN
1456          1988     Gable  CompShg     Plywood     Plywood      Stone
1457          2006     Gable  CompShg     CemntBd     CmentBd        NaN
1458          1996       Hip  CompShg     MetalSd     MetalSd        NaN
1459          1965     Gable  CompShg     HdBoard     HdBoard        NaN

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
0          196.0        Gd        TA      PConc       Gd       TA
1            0.0        TA        TA     CBlock       Gd       TA
2          162.0        Gd        TA      PConc       Gd       TA
3            0.0        TA        TA     BrkTil       TA       Gd
4          350.0        Gd        TA      PConc       Gd       TA
...          ...       ...       ...        ...      ...      ...
1455         0.0        TA        TA      PConc       Gd       TA
1456       119.0        TA        TA     CBlock       Gd       TA
1457         0.0        Ex        Gd      Stone       TA       Gd
1458         0.0        TA        TA     CBlock       TA       TA
1459         0.0        Gd        TA     CBlock       TA       TA

     BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  \
0              No          GLQ         706          Unf           0
1              Gd          ALQ         978          Unf           0
2              Mn          GLQ         486          Unf           0
3              No          ALQ         216          Unf           0
4              Av          GLQ         655          Unf           0
...           ...          ...         ...          ...         ...
1455           No          Unf           0          Unf           0
1456           No          ALQ         790          Rec         163
1457           No          GLQ         275          Unf           0
1458           Mn          GLQ          49          Rec        1029
1459           No          BLQ         830          LwQ         290

      BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  \
0           150          856    GasA        Ex          Y      SBrkr
1           284         1262    GasA        Ex          Y      SBrkr
2           434          920    GasA        Ex          Y      SBrkr
3           540          756    GasA        Gd          Y      SBrkr
4           490         1145    GasA        Ex          Y      SBrkr
...         ...          ...     ...       ...        ...        ...
1455        953          953    GasA        Ex          Y      SBrkr
1456        589         1542    GasA        TA          Y      SBrkr
1457        877         1152    GasA        Ex          Y      SBrkr
1458          0         1078    GasA        Gd          Y      FuseA
1459        136         1256    GasA        Gd          Y      SBrkr

      1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
0          856       854             0       1710             1             0
1         1262         0             0       1262             0             1
2          920       866             0       1786             1             0
3          961       756             0       1717             1             0
4         1145      1053             0       2198             1             0
...        ...       ...           ...        ...           ...           ...
1455       953       694             0       1647             0             0
1456      2073         0             0       2073             1             0
1457      1188      1152             0       2340             0             0
1458      1078         0             0       1078             1             0
1459      1256         0             0       1256             1             0

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  \
0            2         1             3             1          Gd
1            2         0             3             1          TA
2            2         1             3             1          Gd
3            1         0             3             1          Gd
4            2         1             4             1          Gd
...        ...       ...           ...           ...         ...
1455         2         1             3             1          TA
1456         2         0             3             1          TA
1457         2         0             4             1          Gd
1458         1         0             2             1          Gd
1459         1         1             3             1          TA

      TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt  \
0                8        Typ           0         NaN     Attchd       2003.0
1                6        Typ           1          TA     Attchd       1976.0
2                6        Typ           1          TA     Attchd       2001.0
3                7        Typ           1          Gd     Detchd       1998.0
4                9        Typ           1          TA     Attchd       2000.0
...            ...        ...         ...         ...        ...          ...
1455             7        Typ           1          TA     Attchd       1999.0
1456             7       Min1           2          TA     Attchd       1978.0
1457             9        Typ           2          Gd     Attchd       1941.0
1458             5        Typ           0         NaN     Attchd       1950.0
1459             6        Typ           0         NaN     Attchd       1965.0

     GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
0             RFn           2         548         TA         TA          Y
1             RFn           2         460         TA         TA          Y
2             RFn           2         608         TA         TA          Y
3             Unf           3         642         TA         TA          Y
4             RFn           3         836         TA         TA          Y
...           ...         ...         ...        ...        ...        ...
1455          RFn           2         460         TA         TA          Y
1456          Unf           2         500         TA         TA          Y
1457          RFn           1         252         TA         TA          Y
1458          Unf           1         240         TA         TA          Y
1459          Fin           1         276         TA         TA          Y

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0              0           61              0          0            0
1            298            0              0          0            0
2              0           42              0          0            0
3              0           35            272          0            0
4            192           84              0          0            0
...          ...          ...            ...        ...          ...
1455           0           40              0          0            0
1456         349            0              0          0            0
1457           0           60              0          0            0
1458         366            0            112          0            0
1459         736           68              0          0            0

      PoolArea PoolQC  Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
0            0    NaN    NaN         NaN        0       2    2008       WD
1            0    NaN    NaN         NaN        0       5    2007       WD
2            0    NaN    NaN         NaN        0       9    2008       WD
3            0    NaN    NaN         NaN        0       2    2006       WD
4            0    NaN    NaN         NaN        0      12    2008       WD
...        ...    ...    ...         ...      ...     ...     ...      ...
1455         0    NaN    NaN         NaN        0       8    2007       WD
1456         0    NaN  MnPrv         NaN        0       2    2010       WD
1457         0    NaN  GdPrv        Shed     2500       5    2010       WD
1458         0    NaN    NaN         NaN        0       4    2010       WD
1459         0    NaN    NaN         NaN        0       6    2008       WD

     SaleCondition  SalePrice
0           Normal     208500
1           Normal     181500
2           Normal     223500
3          Abnorml     140000
4           Normal     250000
...            ...        ...
1455        Normal     175000
1456        Normal     210000
1457        Normal     266500
1458        Normal     142125
1459        Normal     147500

[1460 rows x 81 columns]>

In [29]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("Numerical columns:", len(numerical_cols))
print("Categorical columns:", len(categorical_cols))

Numerical columns: 38
Categorical columns: 43

In [30]:
numerical_cols.remove('Id')

In [31]:
missing = df.isnull().mean().sort_values(ascending=False)
missing = missing[missing > 0]
print(missing)

PoolQC          0.995205
MiscFeature     0.963014
Alley           0.937671
Fence           0.807534
MasVnrType      0.597260
FireplaceQu     0.472603
LotFrontage     0.177397
GarageQual      0.055479
GarageFinish    0.055479
GarageType      0.055479
GarageYrBlt     0.055479
GarageCond      0.055479
BsmtFinType2    0.026027
BsmtExposure    0.026027
BsmtCond        0.025342
BsmtQual        0.025342
BsmtFinType1    0.025342
MasVnrArea      0.005479
Electrical      0.000685
dtype: float64

In [32]:
none_cols = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu',
             'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
             'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
             'MasVnrType']

for col in none_cols:
    df[col] = df[col].fillna('None')

In [33]:
zero_cols = ['GarageYrBlt', 'MasVnrArea']

for col in zero_cols:
    df[col] = df[col].fillna(0)

In [34]:
df['LotFrontage'] = df.groupby('Neighborhood')['LotFrontage'].transform(lambda x: x.fillna(x.median()))

In [35]:
df['Electrical'] = df['Electrical'].fillna(df['Electrical'].mode()[0])

In [36]:
print("Remaining missing values:", df.isnull().sum().sum())

Remaining missing values: 0

In [37]:
# New Features
df['HouseAge'] = df['YrSold'] - df['YearBuilt']
df['TotalSF'] = df['1stFlrSF'] + df['2ndFlrSF'] + df['TotalBsmtSF']

df[['HouseAge', 'TotalSF']].describe()

          HouseAge       TotalSF
count  1460.000000   1460.000000
mean     36.547945   2567.048630
std      30.250152    821.714421
min       0.000000    334.000000
25%       8.000000   2009.500000
50%      35.000000   2474.000000
75%      54.000000   3004.000000
max     136.000000  11752.000000

In [38]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print("Total categorical columns:", len(categorical_cols))

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print("Shape before encoding:", df.shape)
print("Shape after encoding:", df_encoded.shape)

Total categorical columns: 43
Shape before encoding: (1460, 83)
Shape after encoding: (1460, 263)

In [39]:
df_encoded.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,HouseAge,TotalSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Pave,Alley_None,Alley_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,Utilities_NoSeWa,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Mod,LandSlope_Sev,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_IDOTRR,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Exterior1st_AsphShn,Exterior1st_BrkComm,Exterior1st_BrkFace,Exterior1st_CBlock,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing,Exterior2nd_AsphShn,Exterior2nd_Brk Cmn,Exterior2nd_BrkFace,Exterior2nd_CBlock,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Other,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,MasVnrType_BrkFace,MasVnrType_None,MasVnrType_Stone,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Fa,ExterCond_Gd,ExterCond_Po,ExterCond_TA,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_None,BsmtQual_TA,BsmtCond_Gd,BsmtCond_None,BsmtCond_Po,BsmtCond_TA,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtExposure_None,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_None,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_None,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,HeatingQC_Fa,HeatingQC_Gd,HeatingQC_Po,HeatingQC_TA,CentralAir_Y,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,FireplaceQu_Fa,FireplaceQu_Gd,FireplaceQu_None,FireplaceQu_Po,FireplaceQu_TA,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf,GarageQual_Fa,GarageQual_Gd,GarageQual_None,GarageQual_Po,GarageQual_TA,GarageCond_Fa,GarageCond_Gd,GarageCond_None,GarageCond_Po,GarageCond_TA,PavedDrive_P,PavedDrive_Y,PoolQC_Fa,PoolQC_Gd,PoolQC_None,Fence_GdWo,Fence_MnPrv,Fence_MnWw,Fence_None,MiscFeature_None,MiscFeature_Othr,MiscFeature_Shed,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003.0,2,548,0,61,0,0,0,0,0,2,2008,208500,5,2566,False,False,True,False,True,True,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976.0,2,460,298,0,0,0,0,0,0,5,2007,181500,31,2524,False,False,True,False,True,True,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001.0,2,608,0,42,0,0,0,0,0,9,2008,223500,7,2706,False,False,True,False,True,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998.0,3,642,0,35,272,0,0,0,0,2,2006,140000,91,2473,False,False,True,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000.0,3,836,192,84,0,0,0,0,0,12,2008,250000,8,3343,False,False,True,False,True,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False

In [40]:
from sklearn.preprocessing import StandardScaler

# Scale karne ke liye numeric columns select karo (target aur Id chhod kar)
scale_cols = df_encoded.select_dtypes(include=['int64', 'float64']).columns.tolist()
scale_cols = [col for col in scale_cols if col not in ['Id', 'SalePrice']]

scaler = StandardScaler()
df_encoded[scale_cols] = scaler.fit_transform(df_encoded[scale_cols])

df_encoded[scale_cols].describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,HouseAge,TotalSF
count,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03,1.460000e+03
mean,-8.455945e-17,2.920039e-16,-5.840077e-17,1.387018e-16,3.540547e-16,1.046347e-15,4.496860e-15,-3.893385e-17,-2.433366e-17,-3.406712e-17,-6.600504e-17,2.457699e-16,6.509253e-17,-1.825024e-17,1.216683e-17,-1.277517e-16,2.311697e-17,2.433366e-17,1.180182e-16,2.083569e-17,2.141362e-16,4.501726e-16,-1.022014e-16,-4.866731e-18,1.764190e-16,1.216683e-16,-1.216683e-17,5.596741e-17,3.041707e-17,-2.311697e-17,4.866731e-18,5.475072e-17,1.946692e-17,-2.676702e-17,7.543433e-17,3.567436e-14,5.110068e-17,-2.409032e-16
std,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00,1.000343e+00
min,-8.725628e-01,-2.194041e+00,-9.237292e-01,-3.688413e+00,-4.112970e+00,-3.287824e+00,-1.689368e+00,-5.707501e-01,-9.730182e-01,-2.886528e-01,-1.284176e+00,-2.411167e+00,-2.144172e+00,-7.951632e-01,-1.202417e-01,-2.249120e+00,-8.199644e-01,-2.410610e-01,-2.841822e+00,-7.616207e-01,-3.514952e+00,-4.751486e+00,-2.780469e+00,-9.512265e-01,-4.120324e+00,-2.365440e+00,-2.212963e+00,-7.521758e-01,-7.044833e-01,-3.593249e-01,-1.163393e-01,-2.702084e-01,-6.869175e-02,-8.768781e-02,-1.969111e+00,-1.367655e+00,-1.208604e+00,-2.718479e+00
25%,-8.725628e-01,-4.548501e-01,-2.969908e-01,-7.951515e-01,-5.171998e-01,-5.719226e-01,-8.656586e-01,-5.707501e-01,-9.730182e-01,-2.886528e-01,-7.793259e-01,-5.966855e-01,-7.261556e-01,-7.951632e-01,-1.202417e-01,-7.347485e-01,-8.199644e-01,-2.410610e-01,-1.026041e+00,-7.616207e-01,-1.062465e+00,-2.114536e-01,-9.341298e-01,-9.512265e-01,1.968071e-01,-1.026858e+00,-6.479160e-01,-7.521758e-01,-7.044833e-01,-3.593249e-01,-1.163393e-01,-2.702084e-01,-6.869175e-02,-8.768781e-02,-4.891101e-01,-6.144386e-01,-9.440523e-01,-6.787512e-01
50%,-1.631095e-01,-8.903656e-03,-1.040633e-01,-7.183611e-02,-5.171998e-01,5.737148e-02,4.425864e-01,-5.707501e-01,-1.319022e-01,-2.886528e-01,-2.031633e-01,-1.503334e-01,-1.956933e-01,-7.951632e-01,-1.202417e-01,-9.797004e-02,-8.199644e-01,-2.410610e-01,7.897405e-01,-7.616207e-01,1.637791e-01,-2.114536e-01,-3.186833e-01,6.004949e-01,2.386996e-01,3.117246e-01,3.284429e-02,-7.521758e-01,-3.270298e-01,-3.593249e-01,-1.163393e-01,-2.702084e-01,-6.869175e-02,-8.768781e-02,-1.191097e-01,1.387775e-01,-5.118902e-02,-1.132760e-01
75%,3.098594e-01,4.370428e-01,1.087080e-01,6.514792e-01,3.817427e-01,9.516316e-01,9.271216e-01,3.383686e-01,5.891327e-01,-2.886528e-01,5.450557e-01,5.491227e-01,5.915905e-01,8.731117e-01,-1.202417e-01,4.974036e-01,1.107810e+00,-2.410610e-01,7.897405e-01,1.227585e+00,1.637791e-01,-2.114536e-01,2.967633e-01,6.004949e-01,2.916164e-01,3.117246e-01,4.820057e-01,5.886506e-01,3.221901e-01,-3.593249e-01,-1.163393e-01,-2.702084e-01,-6.869175e-02,-8.768781e-02,6.208910e-01,8.919936e-01,5.771222e-01,5.319380e-01
max,3.147673e+00,1.082759e+01,2.051827e+01,2.821425e+00,3.078570e+00,1.282839e+00,1.217843e+00,8.285201e+00,1.140575e+01,8.851638e+00,4.004295e+00,1.152095e+01,9.132681e+00,3.936963e+00,1.164775e+01,7.855574e+00,4.963359e+00,8.138680e+00,2.605522e+00,3.216791e+00,6.294997e+00,8.868612e+00,4.604889e+00,3.703938e+00,3.114603e-01,2.988889e+00,4.421526e+00,6.087635e+00,7.554198e+00,8.675309e+00,1.721723e+01,8.341462e+00,1.830618e+01,3.116527e+01,2.100892e+00,1.645210e+00,3.288781e+00,1.118162e+01

In [41]:
correlations = df_encoded.corr()['SalePrice'].sort_values(ascending=False)
print(correlations.head(15))

SalePrice           1.000000
OverallQual         0.790982
TotalSF             0.782260
GrLivArea           0.708624
GarageCars          0.640409
GarageArea          0.623431
TotalBsmtSF         0.613581
1stFlrSF            0.605852
FullBath            0.560664
TotRmsAbvGrd        0.533723
YearBuilt           0.522897
YearRemodAdd        0.507101
Foundation_PConc    0.497734
MasVnrArea          0.472614
Fireplaces          0.466929
Name: SalePrice, dtype: float64

In [42]:
print(correlations.tail(10))

HeatingQC_TA        -0.312677
Foundation_CBlock   -0.343263
GarageType_Detchd   -0.354141
MasVnrType_None     -0.367456
GarageFinish_Unf    -0.410608
BsmtQual_TA         -0.452394
FireplaceQu_None    -0.471908
KitchenQual_TA      -0.519298
HouseAge            -0.523350
ExterQual_TA        -0.589044
Name: SalePrice, dtype: float64

In [43]:
# Log Transformation on sekewed features
from scipy.stats import skew

skewed_feats = df_encoded[scale_cols].apply(lambda x: skew(x.dropna()))
skewed_feats = skewed_feats.sort_values(ascending=False)
print(skewed_feats.head(15))

MiscVal          24.451640
PoolArea         14.813135
LotArea          12.195142
3SsnPorch        10.293752
LowQualFinSF      9.002080
KitchenAbvGr      4.483784
BsmtFinSF2        4.250888
ScreenPorch       4.117977
BsmtHalfBath      4.099186
EnclosedPorch     3.086696
MasVnrArea        2.674865
OpenPorchSF       2.361912
LotFrontage       2.210685
TotalSF           1.774874
BsmtFinSF1        1.683771
dtype: float64

In [44]:
# Sale price Sekewness
print("SalePrice skewness:", skew(df['SalePrice']))

SalePrice skewness: 1.880940746034036

In [45]:
# Target  log-transform
df_encoded['SalePrice_log'] = np.log1p(df_encoded['SalePrice'])

# Highly skewed numeric log-transform
high_skew = skewed_feats[abs(skewed_feats) > 0.75].index

for feat in high_skew:
    df_encoded[feat] = np.log1p(df_encoded[feat])

print("Log-transformation done for", len(high_skew), "features")

Log-transformation done for 23 features

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [46]:
print("SalePrice_log skewness:", skew(df_encoded['SalePrice_log']))

SalePrice_log skewness: 0.12122191311528363

In [47]:
from sklearn.model_selection import train_test_split

# Target: SalePrice_log
# Features:remove SalePrice and SalePrice_log both remove from x
X = df_encoded.drop(columns=['SalePrice', 'SalePrice_log', 'Id'])
y = df_encoded['SalePrice_log']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (1168, 261)
X_test: (292, 261)
y_train: (1168,)
y_test: (292,)

In [48]:
# Poora processed dataset (train+test combined, split se pehle wala) save karo
df_encoded.to_csv('/content/drive/MyDrive/14 days of ML/Feature Engneering/ames_housing_processed.csv', index=False)

# Train/test splits ko pickle me save karo (taaki dobara load karke seedha model training kar sako)
import pickle

with open('/content/drive/MyDrive/14 days of ML/Feature Engneering/ames_train_test_split.pkl', 'wb') as f:
    pickle.dump((X_train, X_test, y_train, y_test), f)

print("Saved successfully!")

Saved successfully!